use swiggy;

-- 1. Which restaurant of abohar is visited by least number of people?

SELECT name 
FROM restaurants
WHERE city = "abohar" AND rating_count = 
(SELECT min(rating_count) FROM restaurants WHERE city = "abohar")
LIMIT 1;


-- 2. Which restaurant has generated maximum revenue all over india?

SELECT name, (rating_count*cost) as REVENUE 
FROM restaurants 
WHERE (rating_count * cost) = ( Select max(rating_count*cost) FROM restaurants);

-- 3. How many restaurants are having rating more than the average rating?

SELECT count(name)
FROM restaurants 
WHERE rating> ( select avg(rating) from restaurants );


-- 4. Which restaurant of Delhi has generated most revenue?

SELECT name, (rating_count*cost) as REVENUE
FROM restaurants 
WHERE city="Delhi"
and (rating_count*cost)= (Select max(rating_count*cost) from restaurants where city="Delhi");


-- 5. Which restaurant chain has maximum number of restaurants?

Select count(name),name
FROM restaurants 
GROUP BY name ORDER BY count(name) DESC LIMIT 10 ;


-- 6. Which restaurant chain has generated maximum revenue?

SELECT name, sum( rating_count*cost) as REVENUE
FROM restaurants
GROUP BY name ORDER BY sum( rating_count*cost) DESC LIMIT 1;


-- 7. Which city has maximum number of restaurants?

SELECT city , count(*) as 'no_of_restaurants' FROM restaurants
GROUP BY city ORDER BY count(*) DESC LIMIT 10;


-- 8. Which city has generated maximum revenue all over india?

SELECT city , sum(rating_count * cost) as 'REVENUE' FROM restaurants
GROUP BY city ORDER BY sum(rating_count*cost) DESC LIMIT 10;


-- 9. List 10 least expensive cuisines?

SELECT cuisine ,  AVG(cost) as 'avg_cost' FROM restaurants
GROUP BY cuisine 
ORDER BY avg_cost ASC LIMIT 10;


-- 10. List 10 most expensive cuisines?

SELECT cuisine ,  AVG(cost) as 'avg_cost' FROM restaurants
GROUP BY cuisine 
ORDER BY avg_cost DESC LIMIT 10;


-- 11. Which city is having Biryani as most popular cuisine

SELECT city, avg(cost), count(*) as 'restaurants' FROM restaurants
WHERE cuisine = 'Biryani'
GROUP BY city
ORDER BY restaurants DESC;


-- 12. List top 10 unique restaurants with unique name only throughout the dataset as
-- per generate maximum revenue (Single restaurant with that name)

SELECT name, sum(cost * rating_count) as 'revenue' FROM restaurants 
GROUP BY name HAVING count(name) = 1 
ORDER BY revenue DESC LIMIT 10;




-- WINDOW FUNCTION

-- 1. Rank every restaurant from most expensive to least expensive

SELECT name,cost, RANK() OVER(ORDER BY COST DESC) as "RANK" FROM restaurants;


-- 2. Rank every restaurant from most visited to least visited

SELECT name,rating_count, RANK() OVER(ORDER BY RATING_COUNT DESC) as "RANK" FROM restaurants;


-- 3. Rank every restaurant from most expensive to least expensive as per their city

SELECT name,cost,city,RANK() OVER(PARTITION BY city ORDER BY COST DESC)as "RANK" FROM restaurants;


-- 4. Dense-rank every restaurant from most expensive to least expensive as per their city

SELECT name,cost,city, DENSE_RANK() OVER(PARTITION BY city ORDER BY cost DESC )as "DENSE_RANK" FROM restaurants;


-- 5 Rank the restaurant based on their prices (most to least exp) 
-- as per the cuisine(row_number,dense_rank,rank)

SELECT name,cost,cuisine, RANK() OVER( PARTITION BY cuisine ORDER BY (cost) DESC) as "RANK",
DENSE_RANK() OVER( PARTITION BY cuisine ORDER BY (cost) DESC) as "DENSE_RANK",
ROW_NUMBER() OVER( PARTITION BY cuisine ORDER BY (cost) DESC) as "ROW_NUMBER" FROM restaurants;


-- 6. Row-number every restaurant from most expensive to least expensive as per their city

SELECT name,cost,city, ROW_NUMBER() OVER(PARTITION BY city ORDER BY cost DESC) as "ROW_NUMBER" FROM restaurants;


-- 7. Rank every restaurant from most expensive to least expensive as per 
-- their city along with its city [Adilabad - 1, Adilabad - 2]

SELECT name,cost, CONCAT(CITY,"-",RANK() OVER(PARTITION BY city ORDER BY cost DESC)) AS "RANK" FROM restaurants;


-- 8. Find top 5 restaurants of every city as per their revenue

SELECT name,city,(rating_count*cost) as revenue FROM(
SELECT  name,city,rating_count,cost, rating_count*cost,ROW_NUMBER() 
OVER(PARTITION BY CITY ORDER BY rating_count*cost DESC) as 'RANKS'
FROM restaurants
) t WHERE t.RANKS < 6
ORDER BY revenue DESC LIMIT 5;


-- 9. Find top 5 restaurants of every cuisine as per their revenue

SELECT name,cuisine,(rating_count*cost) as revenue FROM 
(SELECT name,cuisine,rating_count,cost,RATING_COUNT*COST AS "REVENUE", ROW_NUMBER() 
OVER(PARTITION BY CUISINE ORDER BY RATING_COUNT*COST DESC) AS "RANKS"
 FROM RESTAURANTS) AS T
 WHERE T.RANKS<6
 ORDER BY revenue DESC LIMIT 5;


-- 10. List the top 5 cuisines as per the revenue generated by top 5 restaurants of every cuisine

SELECT CUISINE,SUM(RATING_COUNT*COST) as revenue FROM 
(SELECT cuisine,rating_count,cost,(RATING_COUNT*COST) AS REV, ROW_NUMBER() 
OVER(PARTITION BY CUISINE ORDER BY (RATING_COUNT*COST) DESC) AS "RANK" FROM RESTAURANTS) AS T
WHERE T.RANK<6
GROUP BY CUISINE;


-- 11. List the top 5 restaurants as per their revenue generated by the top 5 restaurants of every city

SELECT name,sum(rating_count*cost) AS REVENUE from
(SELECT name,rating_count,cost, ROW_NUMBER() OVER(PARTITION BY city ORDER BY (rating_count * cost)
desc) as " RANKS"  FROM restaurants) as t
WHERE T.RANKS < 6
GROUP BY name
ORDER BY REVENUE DESC
LIMIT 5 ;


-- 12. What is the total revenue generated by top 1% restaurants

SELECT  SUM(rating_count*cost) from
(SELECT *, (RATING_COUNT*COST) AS REVENUE, ROW_NUMBER() 
OVER( ORDER BY (RATING_COUNT*COST) DESC) AS "RANK" FROM restaurants) AS T
WHERE T.RANK <= (SELECT ceil(COUNT(*)*0.01) FROM restaurants);


-- 13. What % of revenue is generated by top 20% of restaurants with respect to total revenue?

WITH
q1 as 
(SELECT SUM(rating_count*cost) as "top_revenue" FROM 
(SELECT rating_count,cost,(rating_count*cost) as revenue, ROW_NUMBER() 
OVER(ORDER BY rating_count*cost DESC) AS "RANK" FROM restaurants) AS T
WHERE T.RANK <= (SELECT ceil(COUNT(*)*0.20) FROM restaurants)),

q2 as 
(SELECT SUM(rating_count*cost) as 'total_revenue' FROM restaurants)

select round((top_revenue/total_revenue)*100) as " revenue %" from q1 , q2;


